server:
  port: 4050

spring:
  rabbitmq:
    host: 192.168.61.129
    port: 5672
    username: zy
    password: zy

sms:
  aliyun:
    accessKey: accessKey
    secretKey: secretKey
    channels:
      loginCodeChannel: SMS_34630023